# ========================================
#        ML4W-style Hyprlock Config
# ========================================

# Cache Folder
$ml4w_cache_folder = $HOME/.cache/ml4w/hyprland-dotfiles

# Source colors
source = colors.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot # Or use 'screenshot' for current desktop
    color = rgba(0,0,0,0.0) # Transparent background for blur to show
    blur_passes = 4 # Higher for more blur (2-4 is common)
    blur_size = 5 # Adjust for intensity
    # Other settings like contrast, brightness, etc., can be tuned here
    brightness = 1
    # blur_size = 7
    # blur_passes = 2
}

# Input field
input-field {
    size = 200, 50
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    inner_color = $primary
    font_color = $on_primary
    font_family = Fira Semibold
    outer_color = $on_primary
    outline_thickness = 3
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    rounding = 10
    check_color = $primary
    fail_color = $error
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -20
    halign = center
    valign = center
    shadow_passes = 10
    shadow_size = 20
    shadow_color = $shadow
    shadow_boost = 1.6
}

# Clock
label {
    text = cmd[update:1000] echo "$TIME"
    color = $foreground
    font_size = 55
    font_family = Fira Semibold
    position = -100, 70
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

# Username
label {
    text = ⨂
    color = $foreground
    font_size = 20
    font_family = Fira Semibold
    position = -100, 160
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

